name: Main Build and Test

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install libgcrypt
        run: sudo apt install -y libgcrypt-dev
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build
        uses: threeal/cmake-action@v2.1.0
      - name: Test
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: build
          build-config: Debug
